version: '3.8'

services:
  asterisk:
    build: ./asterisk
    environment:
      - ASTERISK_UID=1000
      - ASTERISK_GID=1000
    volumes:
      - ./asterisk/config:/etc/asterisk
      - /dev/shm:/dev/shm
    cap_add:
      - SYS_ADMIN
    # Map SIP (UDP 5060), AMI (TCP 5038), and RTP (UDP 10000-10100) to the host
    ports:
      - "5060:5060/udp"
      - "5038:5038"
      - "10000-10100:10000-10100/udp"


  web:
    build: ./web
    # Map the Web UI port to host
    ports:
      - "3000:3000"
    depends_on:
      - asterisk
    environment:
      # Connect to Asterisk AMI by service name
      - AMI_HOST=asterisk
      - AMI_PORT=5038
      - AMI_USER=admin
      - AMI_SECRET=amp111
    restart: unless-stopped
