version: '3.8'

services:
  asterisk:
    build: ./asterisk
    environment:
      - ASTERISK_UID=1000
      - ASTERISK_GID=1000
    volumes:
      - ./asterisk/config:/etc/asterisk
      - /dev/shm:/dev/shm
    cap_add:
      - SYS_ADMIN
    # Expose SIP, AMI, and RTP ports for Twilio SIP trunking
    ports:
      - "5060:5060/udp"
      - "5060:5060"
      - "5038:5038"
      # - "10000-20000:10000-20000/udp"


  web:
    build: ./web
    # Map web UI port to host
    ports:
      - "3000:3000"
    depends_on:
      - asterisk
    environment:
      # Connect to the Asterisk container by its service name
      - AMI_HOST=asterisk
      - AMI_PORT=5038
      - AMI_USER=admin
      - AMI_SECRET=amp111
    restart: unless-stopped
